services:
  jupyter:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    entrypoint: jupyter-lab --allow-root --ip=0.0.0.0 --port=1111 --no-browser --NotebookApp.token='' --notebook-dir=/app/workspace
    ports:
      - "1111:1111"
    volumes:
      - ./jupyter:/root/.jupyter
      - ./:/app/
